server:
  port: 8080
spring:
  application:
    name: grabyou
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/grabyou?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
  mvc:
    async:
      request-timeout: 5000000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.study.grabyou.entity
thymeleaf:
  mode: HTML
  encoding: utf-8
  cache: false
  prefix: classpath:/templates/
logging:
  config: classpath:logback.xml
