package rules;

import org.study.grabyou.entity.Event
import org.study.grabyou.enums.EventType
import org.study.grabyou.service.Impl.BlackListService

global BlackListService blackListService

rule "999_all_blackList"
  salience 999
  lock-on-active true
  when
    event:Event()
  then
    EventType eventType = event.getEventType();
    if (blackListService.isInBlackList(event)) {
      event.setDecisionType(3);
      // System.out.println("直接拦截"); //测试使用
      delete(event);
    }
end
