package rules;

import org.study.grabyou.service.impl.DimensionService
import org.study.grabyou.entity.Event
import org.study.grabyou.enums.EventType
import org.study.grabyou.enums.DimensionType
import org.study.grabyou.enums.TimeRange

global DimensionService dimensionService

rule "99_register"
  salience 99
  lock-on-active true
  when
    event:Event(eventType==EventType.REGISTER)
  then
    int cnt1 = dimensionService.calculateNum(event, DimensionType.TELEPHONE, TimeRange.SECOND);

    System.out.println("hello 99_register!");
end
